### ISSUE TITLE
Adding explicit license

### ISSUE THREAD

**Issue by andreaswachs** [borremosch/cobertura-merge#26]
Hi Borre.

Would you consider adding a license to your project? And if so, which one would you add, in that case?

I'd love to use it at work in a Continuous Integration pipeline. We have strict requirements to control all code made by 3rd parties, and without a license, I'm not in the legal OK to fork your repo and use it at work.

**Comment by borremosch** [comment]
Sure, feel free to open a PR with a suggested license and I'll approve
